name: "Roseau Action"
description: "Custom action to execute a Roseau analysis between the last two commits."
author: "Corentin Latappy <corentin.lat@gmail.com>"
branding:
  icon: code
  color: white

inputs:
  report-artifact:
    description: "Whether to upload the Roseau report and which format"
    required: false
    default: "none"

runs:
  using: "composite"
  steps:
    - name: Set up Java
      uses: actions/setup-java@v5
      with:
        distribution: corretto
        java-version: 21

    - name: Checkout code
      uses: actions/checkout@v5
      with:
        fetch-depth: 0

    - name: Prepare both versions
      shell: bash
      run: |
        mkdir versions
        git worktree add versions/previous ${{ github.event.before }}
        git worktree add versions/current ${{ github.sha }}

    - name: Run Roseau
      shell: bash
      run: java -jar $GITHUB_ACTION_PATH/roseau.jar --diff --v1=versions/previous --v2=versions/current --github-action

    - name: Upload Roseau CSV Report
      if: ${{ inputs.report-artifact == 'csv' }}
      uses: actions/upload-artifact@v4
      with:
        name: Roseau CSV Report
        path: report.csv

    - name: Upload Roseau HTML Report
      if: ${{ inputs.report-artifact == 'html' }}
      uses: actions/upload-artifact@v4
      with:
        name: Roseau HTML Report
        path: report.html

    - name: Add summary
      shell: bash
      run: cat report.md >> $GITHUB_STEP_SUMMARY
